-- MySQL Script generated by MySQL Workbench
-- Thu Apr 23 12:09:21 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema flowManageDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `flowManageDB` ;

-- -----------------------------------------------------
-- Schema flowManageDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `flowManageDB` DEFAULT CHARACTER SET utf8 ;
USE `flowManageDB` ;

-- -----------------------------------------------------
-- Table `flowManageDB`.`programa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flowManageDB`.`programa` ;

CREATE TABLE IF NOT EXISTS `flowManageDB`.`programa` (
  `id` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL,
  `programacol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flowManageDB`.`workflow`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flowManageDB`.`workflow` ;

CREATE TABLE IF NOT EXISTS `flowManageDB`.`workflow` (
  `id` VARCHAR(45) NOT NULL,
  `name` VARCHAR(100) NULL,
  `remark` VARCHAR(255) NULL,
  `fk_programa_id` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_programe_id_idx` (`fk_programa_id` ASC) VISIBLE,
  CONSTRAINT `fk_programe_id`
    FOREIGN KEY (`fk_programa_id`)
    REFERENCES `flowManageDB`.`programa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flowManageDB`.`form_templates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flowManageDB`.`form_templates` ;

CREATE TABLE IF NOT EXISTS `flowManageDB`.`form_templates` (
  `id` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL,
  `form` JSON NULL,
  `fk_workflow_id` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_programa_id_idx` (`fk_workflow_id` ASC) VISIBLE,
  CONSTRAINT `fk_programa_id`
    FOREIGN KEY (`fk_workflow_id`)
    REFERENCES `flowManageDB`.`workflow` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flowManageDB`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flowManageDB`.`role` ;

CREATE TABLE IF NOT EXISTS `flowManageDB`.`role` (
  `id` VARCHAR(45) NOT NULL,
  `rolename` VARCHAR(45) NULL,
  `remark` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flowManageDB`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flowManageDB`.`user` ;

CREATE TABLE IF NOT EXISTS `flowManageDB`.`user` (
  `id` VARCHAR(45) NOT NULL,
  `rolename` VARCHAR(45) NULL,
  `remark` VARCHAR(255) NULL,
  `fk_role_id` VARCHAR(45) NULL,
  `tel` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `role_id_idx` (`fk_role_id` ASC) VISIBLE,
  CONSTRAINT `role_id`
    FOREIGN KEY (`fk_role_id`)
    REFERENCES `flowManageDB`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flowManageDB`.`page`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flowManageDB`.`page` ;

CREATE TABLE IF NOT EXISTS `flowManageDB`.`page` (
  `id` VARCHAR(45) NOT NULL,
  `url` VARCHAR(200) NULL,
  `title` VARCHAR(200) NULL,
  `createTime` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flowManageDB`.`role_page`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flowManageDB`.`role_page` ;

CREATE TABLE IF NOT EXISTS `flowManageDB`.`role_page` (
  `id` INT NOT NULL,
  `fk_role_id` VARCHAR(45) NULL,
  `fk_page_id` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `role_id_idx` (`fk_role_id` ASC) VISIBLE,
  INDEX `page_id_idx` (`fk_page_id` ASC) VISIBLE,
  CONSTRAINT `fk_role_id`
    FOREIGN KEY (`fk_role_id`)
    REFERENCES `flowManageDB`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_page_id`
    FOREIGN KEY (`fk_page_id`)
    REFERENCES `flowManageDB`.`page` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flowManageDB`.`dict`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flowManageDB`.`dict` ;

CREATE TABLE IF NOT EXISTS `flowManageDB`.`dict` (
  `iddict` INT NOT NULL,
  `key` VARCHAR(45) NULL,
  `value` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`iddict`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flowManageDB`.`form_field`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flowManageDB`.`form_field` ;

CREATE TABLE IF NOT EXISTS `flowManageDB`.`form_field` (
  `id` INT NOT NULL,
  `fieldtype` VARCHAR(45) NULL,
  `fieldname` VARCHAR(45) NULL,
  `order` INT NULL,
  `fk_templates_id` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_templates_idx` (`fk_templates_id` ASC) VISIBLE,
  CONSTRAINT `fk_templates`
    FOREIGN KEY (`fk_templates_id`)
    REFERENCES `flowManageDB`.`form_templates` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flowManageDB`.`flow_model`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flowManageDB`.`flow_model` ;

CREATE TABLE IF NOT EXISTS `flowManageDB`.`flow_model` (
  `id` VARCHAR(45) NOT NULL COMMENT '工作流模型。绘制玩工作流生成表内容',
  `nodename` VARCHAR(45) NULL,
  `fk_role_id` VARCHAR(45) NULL,
  `pid` VARCHAR(45) NULL COMMENT '上一级id号',
  `fk_template_id` VARCHAR(45) NULL,
  `flowdatacol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_template_id_idx` (`fk_template_id` ASC) VISIBLE,
  INDEX `fk_role_id_idx` (`fk_role_id` ASC) VISIBLE,
  CONSTRAINT `fk_template_id`
    FOREIGN KEY (`fk_template_id`)
    REFERENCES `flowManageDB`.`form_templates` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_flow_role_id`
    FOREIGN KEY (`fk_role_id`)
    REFERENCES `flowManageDB`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flowManageDB`.`work_data_2020`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flowManageDB`.`work_data_2020` ;

CREATE TABLE IF NOT EXISTS `flowManageDB`.`work_data_2020` (
  `id` INT NOT NULL,
  `fk_folw_model` VARCHAR(45) NULL,
  `createTime` DATETIME NULL,
  `r1` VARCHAR(200) NULL,
  `r2` VARCHAR(200) NULL,
  `r3` VARCHAR(200) NULL,
  `r4` VARCHAR(200) NULL,
  `r5` VARCHAR(200) NULL,
  `r6` VARCHAR(200) NULL,
  `r7` VARCHAR(200) NULL,
  `r8` VARCHAR(200) NULL,
  `r9` VARCHAR(200) NULL,
  `r10` VARCHAR(200) NULL,
  `r11` VARCHAR(200) NULL,
  `r12` VARCHAR(200) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_flow_model_idx` (`fk_folw_model` ASC) VISIBLE,
  CONSTRAINT `fk_flow_model`
    FOREIGN KEY (`fk_folw_model`)
    REFERENCES `flowManageDB`.`flow_model` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flowManageDB`.`news`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flowManageDB`.`news` ;

CREATE TABLE IF NOT EXISTS `flowManageDB`.`news` (
  `id` INT NOT NULL,
  `fk_user_id` VARCHAR(45) NULL,
  `htmlTemplate` TEXT NULL,
  `type` VARCHAR(5) NULL COMMENT '分类标记',
  PRIMARY KEY (`id`),
  INDEX `fk_user_id_idx` (`fk_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_id`
    FOREIGN KEY (`fk_user_id`)
    REFERENCES `flowManageDB`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
